// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRP-EjTxC33TqiWwadRS8bbzk0h3IjIJw',
    appId: '1:874888084560:web:8a2de5bc8b87a069db6555',
    messagingSenderId: '874888084560',
    projectId: 'actionlistener-c2cfa',
    authDomain: 'actionlistener-c2cfa.firebaseapp.com',
    storageBucket: 'actionlistener-c2cfa.appspot.com',
    measurementId: 'G-E8XVR997SJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfhlnhCSt28fCk2IAfBvIFjfAx2wJ0-hk',
    appId: '1:874888084560:android:1b3820ba19c3fa00db6555',
    messagingSenderId: '874888084560',
    projectId: 'actionlistener-c2cfa',
    storageBucket: 'actionlistener-c2cfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsW9dsfqLDf7bwH6w3G4MnRbGg7SmvI0I',
    appId: '1:874888084560:ios:8a67178c097d3c49db6555',
    messagingSenderId: '874888084560',
    projectId: 'actionlistener-c2cfa',
    storageBucket: 'actionlistener-c2cfa.appspot.com',
    iosBundleId: 'com.example.actionListner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsW9dsfqLDf7bwH6w3G4MnRbGg7SmvI0I',
    appId: '1:874888084560:ios:0a6e46471035279cdb6555',
    messagingSenderId: '874888084560',
    projectId: 'actionlistener-c2cfa',
    storageBucket: 'actionlistener-c2cfa.appspot.com',
    iosBundleId: 'com.example.actionListner.RunnerTests',
  );
}
